### ISSUE TITLE
#[Derive(EnumInnerAsTrait(MyTrait))] - cast variants to a trait

### ISSUE THREAD

**Issue by nielsle** [DanielKeep/rust-custom-derive#16]
Here is another idea, that could be super useful:

If each variant of an enum has exactly one field, and if each of these fields implement a given trait, then it could be great to be able to cast the enum to the trait.  It could look like this
~~~
trait Hello { fn hello(&self){}}

struct A{_x:f32}
struct B{_y:u32}
impl Hello for A {}
impl Hello for B {}

#[derive(EnumInnerAsTrait(Hello))]
enum Foo { A(A), B(B) }

fn main() {
    let a = Foo::A(A {_x:1.0});
    let b = Foo::B(B {_y:1});
    a.as_trait().hello();
    b.as_trait().hello();
}
~~~
The following could be derived behind the scenes
~~~
pub trait AsTrait {
    type T: ?Sized;
    fn as_trait(&self) -> &Self::T;
}

impl AsTrait for Foo {
    type T=Hello;
    fn as_trait(&self) -> &Self::T {
        match self {
            &Foo::A(ref a) => a as &Self::T,
            &Foo::B(ref b) => b as &Self::T,
        }
    }
}
~~~
I have a feeling that there are some pitfalls in this approcah, but at least the following gist works fine, so for some cases it could work out of the box https://gist.github.com/888cbd1ac4be542bce24a1fadf472566.

PS It would also be great to have mutable references

**Comment by DanielKeep** [comment]
This is published in the 0.1.7 release.
