### ISSUE TITLE
#[derive(StructIterFieldsAsTrait(....))]

### ISSUE THREAD

**Issue by nielsle** [DanielKeep/rust-custom-derive#20]
Here is another idea, that may or may not be possible to implement.

If all the fields of a struct implement a given trait,  then be nice to be able to iterate over fields of a struct as cast to the trait.I must admit that I don't know if  this is even possible, but if it can be done, then it would be great to have something like the following

```
struct A;
struct B;

trait Hello { fn hello(&self) { println!("Hello")} }
impl Hello for A {};
impl Hello for B {};

// #[derive(StructIterFieldsAsTrait(pub iter_hellos -> &Hello)]
struct Foo {a: A, b: B}

fn main() {
    let foo= Foo {a:A, b:B};
    for &h in &foo.iter_fields() {
        h.hello();
    }
}
```

**Comment by DanielKeep** [comment]
Going through the backlog of issues, and I just can't convince myself that this really makes sense.  This is absolutely possible, but I can't think of *any* situation where this would be useful... *except* for serialisation-like usecases, but those are probably better served by `rustc-serialize` or `serde`.  I also feel that if a compelling reason for this exists, it's probably so niche that it'd be better in its own crate anyway.

As such, I'm closing this.
