### ISSUE TITLE
Using non-built-in derive types with custom_derive?

### ISSUE THREAD

**Issue by alexreg** [DanielKeep/rust-custom-derive#23]
I want to use Serde's `Serialize` and `Deserialize` derive types, but I get these errors when compiling:

```
error: macro undefined: 'Serialize!'
   --> src/api/common.rs:105:1
    |
105 | custom_derive! {
    | ^
    |
    = note: this error originates in a macro outside of the current crate

error: macro undefined: 'Deserialize!'
   --> src/api/common.rs:105:1
    |
105 | custom_derive! {
    | ^
    |
    = note: this error originates in a macro outside of the current crate
```

Is there any way around this?

**Comment by DanielKeep** [comment]
This is solved by using the new `macro-attr` v0.2.0 (which is what `custom_derive` was renamed to).  Instead of a whitelist, all macro derivations now use an explicit `!` in their name.
