### ISSUE TITLE
newtype_derive: interior field needs to be pub?

### ISSUE THREAD

**Issue by agrover** [DanielKeep/rust-custom-derive#5]
Having an issue when trying to modularize my project that uses newtype_derive:

```
custom_derive! {
    #[derive(NewtypeFrom, NewtypeAdd, NewtypeSub, NewtypeDeref,
             NewtypeBitAnd, NewtypeNot, NewtypeDiv, NewtypeRem,
             Debug, Clone, Copy, Eq, PartialEq, PartialOrd, Ord)]
    pub struct Sectors(u64);
}
```

I get `error: cannot invoke tuple struct constructor with private fields [E0450]
src/consts.rs:12 pub const MDA_ZONE_SECTORS: Sectors = Sectors(MDA_ZONE_SIZE / SECTOR_SIZE);`

Then, doing what E0450 says I try to change `pub struct Sectors(u64)` to `pub struct Sectors(pub u64)` and I get:

```
error: local ambiguity: multiple parsing options: built-in NTs ty ('t0') or 1 other option.
src/types.rs:23     pub struct Sectors(pub u64);
```

and thought that might suggest a macro-related issue?

**Comment by durka** [comment]
I think there are two bugs here:

- You can't use a tuple struct literal if the fields are private. That in itself has nothing to do with the macro. Provide a public `new()` function if you want it to be constructible from other modules.
- The newtype custom derives can't parse the public field syntax. Ideally this can be fixed.

**Comment by durka** [comment]
Working on a PR for #2.

**Comment by DanielKeep** [comment]
agrover: I'm sorry that this fell through the cracks.
